### ISSUE TITLE
Need error message

### ISSUE THREAD

**Issue by lgladstone** [project8/katydid#107]
In copying the old Katydid wiki pages into the modern docs system, I found this listed on a "known issues" page. If this is still an issue, I'm listing it here so it gets tracked appropriately. If it's not, please close this issue. 

"JSON syntax errors in your configuration file will cause Katydid to exit with an error message. It should specify where the problem is in the json file."

**Comment by evzayas** [comment]
I've always found the json errors to be pretty helpful, such as:

```15:56:27 [ERROR] cessorToolbox.cc(442): An error occurred while connecting signals and slots:
	Signal track from processor tr-proc (a.k.a. track-proc)
	Slot processed-track from processor rootw1 (a.k.a. root-tree-writer)
	Exception caught in KTProcessor::ConnectASignal; signal: track, slot: processed-track
Slot pointer was NULL
	If the signal wrapper cannot be cast correctly, check that the signatures of the signal and slot match exactly.
	If the signal pointer is NULL, you may have the signal name wrong.
	If the slot pointer is NULL, you may have the slot name wrong.
15:56:27 [ERROR] cessorToolbox.cc(150): Unable to make connection <tr-proc:track> --> <rootw1:processed-track>
15:56:27 [ERROR] on/KTRunNymph.cc(38): Unable to configure processor toolbox. Aborting.```

Maybe Noah can confirm whether this kind of error message is the resolution to this (very old) known issue, or did we at some point want something more?

**Comment by nsoblath** [comment]
@evzayas that error message actually applies more to #108, and as you say it already explains the problem, so I closed that issue.

Unfortunately the YAML parser doesn't provide useful information about the location of a syntax error.  There's not much I can do about this, though, so I'll have to mark it as "Won't Fix."  If people want to make a new issue to bring it up again, they can do so.
