### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by lgladstone** [project8/katydid#108]
In copying the old Katydid wiki pages into the modern docs system, I found this listed on a "known issues" page. If this is still an issue, I'm listing it here so it gets tracked appropriately. If it's not, please close this issue. 

"Signal/slot connection errors will cause Katydid to exit with an error message. There are three common variations (missing signal, missing slot, and mismatched signatures), and the error message should tell you how to diagnose what is actually wrong."

**Comment by nsoblath** [comment]
This is already done.
