### ISSUE TITLE
Problems building with Clang

### ISSUE THREAD

**Issue by lgladstone** [project8/katydid#111]
In copying the old Katydid wiki pages into the modern docs system, I found this listed on a "installation issues" page. If this is still an issue, I'm listing it here so it gets tracked appropriately. If it's not, please close this issue.

* Building Katydid with clang (e.g. Mac using Xcode and Boost installed via HomeBrew)
    * Error message: " ./boost/atomic/detail/gcc-atomic.hpp:961:64: error: no matching constructor for initialization of 'storage_type' (aka 'boost::atomics::detail::storage128_type') "
    * Problem observed on a Mac with Boost-1.55.0 installed via HomeBrew.  This problem has been patched for later versions of Boost, but not on the latest version available on HomeBrew.
    * Fix: 
        1. Update Boost.  If already using latest version, try the following.
        1. Download gcc-atomic.hpp and cas128strong.hpp with fixes suggested from:
            - https://github.com/boostorg/atomic/commit/e4bde20f2eec0a51be14533871d2123bd2ab9cf3
            - https://github.com/boostorg/atomic/commit/6bb71fdd8f7cc346d90fb14beb38b7297fc1ffd9

**Comment by nsoblath** [comment]
We moved away from boost::atomic when we adopted C++11, which has its own atomic types.  This is no longer a problem.
