### ISSUE TITLE
Protobuf compile fail

### ISSUE THREAD

**Issue by lgladstone** [project8/katydid#112]
In copying the old Katydid wiki pages into the modern docs system, I found this listed on a "installation issues" page. If this is still an issue, I'm listing it here so it gets tracked appropriately. If it's not, please close this issue.

* Compile fails at 2% with a protobuf problem that looks like this:

    
Linking CXX shared library libMonarchProto.dylib
Undefined symbols for architecture x86_64:
  "google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))", referenced from:
      Protobuf::protobuf_AddDesc_MonarchHeader_2eproto() in MonarchHeader.pb.cc.o
  "google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      Protobuf::MonarchHeader::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in MonarchHeader.pb.cc.o
  "google::protobuf::internal::WireFormatLite::WriteString(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      Protobuf::MonarchHeader::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in MonarchHeader.pb.cc.o
  "google::protobuf::DescriptorPool::FindFileByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      Protobuf::protobuf_AssignDesc_MonarchHeader_2eproto() in MonarchHeader.pb.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Source/Egg/Monarch/Protobuf/libMonarchProto.dylib] Error 1
make[1]: *** [Source/Egg/Monarch/Protobuf/CMakeFiles/MonarchProto.dir/all] Error 2
make: *** [all] Error 2

This is an error related to mixing libc++ and libstdc++.  Protobuf needs to be compiled with the following flags:

CXXFLAGS+="-stdlib=libc++"
LIBS+="-lc++"

For homebrew installing protobuf-2.5.0, do the following:

> brew edit protobuf

and add in the `def install` block the following before anything else:

ENV['CXXFLAGS']="-stdlib=libc++"
ENV['LIBS']="-lc++"

That ought to do it.  Note that word on the street is that this bug is fixed in protobuf-2.5.1-pre, so this will be fixed in the future by somebody else.

**Comment by nsoblath** [comment]
Since protobuf was used for egg2 (i.e. ancient) files, and at this point there's no demand for reading those files, I'm going close this issue as "Won't fix."  If for some reason we need to resurrect the code to read those files in the future, we can deal with it then (if it in fact still exists as a problem).  Thanks for bringing it up so we can close it out properly.
