### ISSUE TITLE
Add slot to TrackProcessing that takes SeqLines as input

### ISSUE THREAD

**Issue by cclaessens** [project8/katydid#131]
We want to use the weighted slope algorithm on points from SeqLines. This processor should convert SeqLines to processed Tracks.

**Comment by cclaessens** [comment]
The LineRef objects from SeqLines do have a slope. But I thought the double cuts is there to remove points that are far away from the track. I don't think there is a need to do that with STF output.

**Comment by guiguem** [comment]
Seems that being able to access the Double cuts algorithm with just KTSparseWaterfallCandidateData will be challenging, as the double cuts uses the slope, intercept and some rescaling factors.
I have changed the logic, so if there is only one slot (KTSparseWaterfallCandidateData), it will stop when trying to do the double-cut.
Not sure if there is a better way: I could comment the double-cuts out for the moment while we rework this thing.

**Comment by guiguem** [comment]
Done in #140
