### ISSUE TITLE
Add new track properties as first-track-properties to multi-peak-events

### ISSUE THREAD

**Issue by cclaessens** [project8/katydid#148]

**Comment by evzayas** [comment]
Done here: https://github.com/project8/katydid/commit/d2043eee89f38be8aac62131e5172cd3fa7237a0

Still need to add these variables to the appropriate writer.

**Comment by guiguem** [comment]
Thanks. Updating the writer would correspond to an update of Cicada.

**Comment by guiguem** [comment]
Updated to Cicada; let's see if it builds

**Comment by guiguem** [comment]
Completed with #158
