### ISSUE TITLE
Split TrackProcessing into two processors

### ISSUE THREAD

**Issue by guiguem** [project8/katydid#151]
TrackProcessing now combines two algorithms that can act on several types of input data.
Among other reasons the fact that one algorithm (double-cut) cannot work with one type of data (SeqLine only) means we should separate them out.

**Comment by guiguem** [comment]
This is up-to-you. I am not sure on which timescale I could get this, but the processor looks terrible and splitting could potentially straightforward.

**Comment by cclaessens** [comment]
If you think it is straight forward and have the time to do that then it would of course be nice. We are still working on many other things to, so right now it wouldn't be holding up the project.
I am just worried that if we keep adding more issues we will never finish this.

**Comment by guiguem** [comment]
Being solved in #131
