### ISSUE TITLE
update ROOT Writers for multi peak events

### ISSUE THREAD

**Issue by cclaessens** [project8/katydid#154]

**Comment by evzayas** [comment]
Relevant commits: https://github.com/project8/katydid/commit/adf80cd406e090250c0a96cb1fb91ff3de78bccd and https://github.com/project8/cicada/commit/538a9e18358a205911efd1269f44d8c5fd80be6d (Cicada). I am not super well versed in the new protocol for updating writers with Cicada, so I would like someone to review it first.

**Comment by guiguem** [comment]
Done with #158
