### ISSUE TITLE
Travis: brew fails to install root quickly

### ISSUE THREAD

**Issue by guiguem** [project8/katydid#169]
Related to: https://github.com/Homebrew/homebrew-core/blob/master/Formula/root.rb#L30
See solution in https://github.com/project8/morpho/blob/develop/.travis.yml

**Comment by guiguem** [comment]
Related: Travis fails to brew install things now.
Laybe we should just get rid of brew and use only the docker containers

**Comment by nsoblath** [comment]
Fix to be released in v2.16
