### ISSUE TITLE
Add YAML <--> KTParam Capabilities

### ISSUE THREAD

**Issue by nsoblath** [project8/katydid#28]

**Comment by nsoblath** [comment]
This is done in Scarab, and we now need to switch KTParam out for scarab::param

**Comment by laroque** [comment]
What is the status of being able to use this? Is the KTParam -> scarab::param basically a find and replace plus some fixing `#include`s or is there subtlety anticipated?

**Comment by nsoblath** [comment]
It looks like the Scarab version currently in Katydid:develop does not have the YAML capabilities.  So Scarab needs to be updated, and then there's a bunch of find-and-replacing and include fixing to change which class is used.  I don't _think_ there's any subtleties to worry about.  If there's any functionality that was added in the KTParam classes it could be added to the scarab::param classes.

**Comment by guiguem** [comment]
It seems that the boolean parameters in a yam file are not taken into account/set to "true" even if the value in the config file is "true", "false", "no", "TRUE".

**Comment by nsoblath** [comment]
This is done in release v2.6.0
