### ISSUE TITLE
single channel time series is in units of ADC values (0->256) instead of in volts.

### ISSUE THREAD

**Issue by pslocum** [project8/katydid#56]
This is not too urgent but it would be helpful to have the real voltages inside Katydid.

**Comment by nsoblath** [comment]
Time series data objects should be real voltages.  There are raw-ts objects
that have ADC values.  If you're looking at the actual time series, and
it's still giving you what appear to be ADC values, it may be that the
digitization parameters in the header of the egg file aren't right.  That's
what's used to convert from ADC values to voltages.

On Mon, Apr 4, 2016 at 3:29 PM pslocum <notifications@github.com> wrote:

> This is not too urgent but it would be helpful to have the real voltages
> inside Katydid.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/project8/katydid/issues/56>
>
-- 
Dr. Noah S. Oblath
Laboratory for Nuclear Science
Massachusetts Institute of Technology
77 Massachusetts Avenue, Bldg. 26-570
Cambridge, MA  02139

Phone: (617) 452-3258
nsoblath@mit.edu
--

**Comment by pslocum** [comment]
Hi Noah,

The digitization parameters look like they are being parsed correctly by
Katydid:

Channel header:
    Number: 0
    Source: locust_mc
    Raw Slice Size: 6667
    Slice Size: 6667
    Slice Stride: 6667
    Record Size: 4194304
    Sample Size: 1
    Data Type Size: 1 bytes
    Data Format: 0
    Bit Depth: 8 bits
    Bit Alignment: 0
    Voltage Offset: -1e-07 V
    Voltage Range: 2e-07 V
    DAC Gain: 1

But then in SingleChannelDAC.hh the "RAW TS" is the same as the "TS"

14:52:14 [ WARN] gleChannelDAC.hh(225): Raw TS:  127  85  128  170  127
85  128  170  127  85  128  171  127  84  128  170  127  85  128  170  127
85  128  170  127  85  128  170  127  85
14:52:14 [ WARN] gleChannelDAC.hh(226): TS:  127  85  128  170  127  85
128  170  127  85  128  171  127  84  128  170  127  85  128  170  127  85
128  170  127  85  128  170  127  85

To get around this I am temporarily doing the normalization outside of
Katydid.  Please let me know if there might be a better approach.

Thanks,
Penny

**Comment by nsoblath** [comment]
The DAC Gain is used to multiply the ADC value, before adding the voltage offset.  Since it's 1 in your file, the values appear unchanged from the digitized values.

There's a function in Scarab (library/utility/digital.hh/cc) that can calculate that for you from the number of digital levels and the voltage range, called get_calib_params. It fills a struct with a variety of useful (for ADC and DAC conversion) parameters. Alternatively, you can calculate it yourself (in the same way the function does).

**Comment by pslocum** [comment]
OK, so this thread might belong under Locust instead.  I am presently using
the get_calib_parameters function in LMCDigitizer.cc like this:

        get_calib_params( 8, 1, -1.e-7, 2.e-7, false, &fParams );

And here is its declaration in Scarab:

SCARAB_API void get_calib_params( unsigned n_bits, unsigned data_type_size,
double v_offset, double v_range, bool bits_r_aligned, dig_calib_params
*params )

Do I need to go into Scarab someplace else to adjust the DAC gain, or am I
looking at the correct function already?

**Comment by pslocum** [comment]
The DAC gain looks perfect in LMCDigitizer.cc:

       get_calib_params( bitDepth, dataTypeSize, vMin, vRange, false,
&fParams );
        printf("dac_gain is %g\n", fParams.dac_gain); getchar();

The output of this is

dac_gain is 7.8125e-10

However if I check the header of the egg3 file read by Katydid, the DAC
gain is reported as 1:

DAC Gain: 1

So it looks like the DAC gain is getting calculated correctly in Locust but
is not being written to the egg3 file header.  Does this sound right?

**Comment by nsoblath** [comment]
Can you please send me an example egg file by email?  I'm sure you've sent one before, but I want to make sure I'm looking at the most up-to-date version.

**Comment by nsoblath** [comment]
I believe the problem is on line 114 of LMCEggWriter.cc.  I probably put that there as a place holder, or something like that.

If that's not the cause, and this symptom still exists, let's move the discussion over to a Locust issue.
