### ISSUE TITLE
Conversion between frequency and power spectrum unreliable for some frequency bounds

### ISSUE THREAD

**Issue by evzayas** [project8/katydid#58]
I'm looking specifically at the CreatePowerSpectrum() method in KTFrequencySpectrumPolar.cc. The comments claim it can accommodate frequency spectra which are symmetric or not, and which cross DC or not. But as far as I can gather every implementation of this function that isn't in validation scripts uses a symmetric frequency spectrum.

In the validation script Test2DDiscrim.cc ([link](https://github.com/project8/katydid/blob/feature/LineFitting/Source/Executables/Validation/Test2DDiscrim.cc)) I create a frequency spectrum from 50 MHz to 150 MHz and convert it to a power spectrum. The result runs from DC to 100 MHz with everything shifted down 50 MHz. If I'm understanding the code correctly, this is because dcBin < 0 and and thus we only enter the first loop (line 126 in KTFrequencySpectrumPolar.cc), essentially copying each bin in order. Except the power spectrum necessarily begins at DC, while the frequency spectrum in this case does not.

I've corrected for this in the validation script by shifting the end result back up by 50 MHz (line 224). But ideally this should be handled correctly by the power spectrum in the first place.

Please let me know any comments about this, because I understand this function is quite important to the beginning of virtually any Katydid analysis, and I want to be very cautious about changing anything.

**Comment by nsoblath** [comment]
There definitely appears to be something wrong.  I'm not 100% sure why you're getting the range shifted down to 0-100 MHz, but I have spotted something that's wrong.  If you can do a little testing we should be able to figure out what's going on.

The line that I know is wrong is line 102.  `GetRangeMin()` and `GetRangeMax()` should be replaced by `minFreq` and `maxFreq`, respectively.

We need to determine what values it's coming up with for `minFreq` and `maxFreq`.  You can see how they're calculated in the lines above that, and it would be useful to do some testing where you print out the various values at each stage.  Can you please try that and post the results?

**Comment by evzayas** [comment]
I've made the change Noah suggested in line 102 and found the point of confusion. In the case where both GetRangeMax() and GetRangeMin() are positive, maxFreq = GetRangeMax() and minFreq = GetRangeMin() always (this can be easily deduced from lines 93-100, but I've confirmed it with testing); so this change made no difference at least in my case.

The confusion is in line 111, comparing dcBin and size(). With a frequency spectrum from 50 MHz to 150 MHz, we get dcBin = -50 and size() = 100. However, the conditional on line 111: dcBin >= size() returns true. I replaced size() with lastPosFreqBin as they are set equal immediately before; and still, dcBin >= lastPosFreqBin returns true.

I suppose it's because the comparator is between an int and an unsigned. I'm not sure why that would cause confusion, but I've replaced all the unsigneds with ints and now indeed dcBin < 0.

What's maybe more amusing is that this doesn't actually change the output power spectrum. In the old case, we had:
- firstPos = 100
- lastPos = 100
- firstNeg = 0
- lastNeg = 100

after falsely evaluating the conditional. So, the loop at line 126 was skipped entirely and the loop at line 132 assigned bins from DC to 100 MHz. In the new case, we instead have:
- firstPos = 0
- lastPos = 100
- firstNeg = -50
- lastNeg = -50

This time the loop at 132 is skipped entirely, and 126 assigns the bins in order from DC to 100 MHz - exactly the same result.

Really what we should have in this case is 150 bins, with zero power in the first 50. The number of bins should always be the largest absolute frequency divided by the bin width (i.e. line 99 removed). And we should always ensure firstPos = lastNeg, which in this case should be -50.

**Comment by nsoblath** [comment]
We have two semi-independent problems to solve: making sure the frequency range of the power spectrum is correct, and making sure we're using the bins of the frequency spectrum correctly.  So far the latter is working, while the former is still a problem.

These are the changes that I think you have made or should make, so far:
1 lines 107-110: replace `unsigned` with `int`
1 line 111: add `(int)` before `size()` to ensure signed ints are used for the comparison
1 line 102: GetRangeMin() and GetRangeMax() should be replaced by minFreq and maxFreq, respectively

Changes 1 and 2 should give us the correct mapping of bins from the frequency spectrum onto the bins of the power spectrum.

Change 3 should give you the correct frequency range for the power spectrum (50-150 MHz, in your test case).  But from what you said above, it seems like that's still not working.  The problem has to be somewhere in the block from line 93 to line 100.  After that, the frequency range of the power spectrum is set (at line 102).  So if `minFreq` and `maxFreq` are 50 and 150 MHz, respectively, at line 102, then that's what the frequency range of your power spectrum should be.

The loops below line 124 operate based on bin number, not frequency value.  So even if they go from 0 to 100, that has nothing to do with the frequency range, which should already be 50-150 MHz.

**Comment by evzayas** [comment]
I believe it's resolved now. Noah, you're correct; those are precisely the changes that I have made. What I didn't account for is the fact that the power spectrum *does not* necessarily start at DC (the comment in line 89 says it does). Indeed the minimum frequency is 50 MHz and this quantity is accessible to processors and validation scripts so getting the correct result is no problem. I've changed the comments at the top of the method to be more accurate.

**Comment by nsoblath** [comment]
Sounds good.  It sounds like everything is resolved, so I'll close the issue.  If there's anything else still in question, please reopen.

**Comment by nsoblath** [comment]
For the record, this was moved to a hotfix and the same change was made to KTFrequencySpectrumFFTW.  The updates are available in v2.4.2.

**Comment by laroque** [comment]
I redid the merge into develop so that the tag v2.4.2 would be a parent of develop

**Comment by nsoblath** [comment]
I use a git GUI called SourceTree for much of my basic git use, including git-flow command sequences.  I don't know if it does it in exactly the same way as the command-line git-flow git extension.  It has some sequence of commands that get called when you finish a hotfix or release, and they do always seem to result in develop not having the tag as an ancestor.  I don't know if that's intentional or not.
