### ISSUE TITLE
The --help-config option doesn't work

### ISSUE THREAD

**Issue by laroque** [project8/katydid#60]
Expected behavior:
Parse a provided config file
Print out the available CLI configuration parameters
Exit

Observed behavior:
executes provided config file

Reproduce:
`/path/to/Katydid --help-config -c /path/to/any/config/file.json`

**Comment by nsoblath** [comment]
This turns out to have been a problem in Nymph that was created when the old parameter data structures were replaced with KTParam, and I was lazy and didn't reimplement this functionality.  It's now been reimplemented in Nymph v1.0.5, and Katydid commit 335b3009a657d402b2018e09309fa35c4dab19cd.
