### ISSUE TITLE
RunDuration units are incorrect in the RSA Reader

### ISSUE THREAD

**Issue by ldeviveiros** [project8/katydid#63]
The header variable RunDuration is a stored as an unsigned integer, but it seems to be in units of seconds; we should thus store it as a double.

**Comment by nsoblath** [comment]
In fine Project 8 tradition, started with the very first iterations of Mantis and Monarch before I had touched either one, RunDuration is in ms, not s.

**Comment by ldeviveiros** [comment]
In that case, the RSA data has is being saved with the wrong units.  I will fix that.  There was very little documentation on the units on the code, I will try adding some to whatever I change.  So we should stick to integers for RunDuration (ms being enough resolution, I guess)?

**Comment by nsoblath** [comment]
I think we should stay with integers for the RunDuration.  There are other times that are in seconds that are doubles (e.g. the TimeInRun and TimeInAcq fields in the slice header).  You're certainly right about the dismal state of the documentation.  Some things are documented, but a lot of others have been missed.

**Comment by ldeviveiros** [comment]
#65 This pull request should fix RunDuration - it's now in ms everywhere
