### ISSUE TITLE
Generate pdf files of Spectrograms

### ISSUE THREAD

**Issue by guiguem** [project8/katydid#67]
Instead of generating root files which contains the TH2 of an event, one should be able to generate a pdf file. A flag should be added into the config file to trigger the generation of a generic TCanvas wit an appropriate name (run name + eventID+name of the Spectrogram component), the plotting of the histo and the SaveAs(...) call in the KTROOTSpectrogramWriter.

**Comment by evzayas** [comment]
I have implemented something of this sort on the feature/EventViewer branch now. The example config file `DisplayAndSaveSpectrograms.yaml` uses the new feature, which allows you to save every TCanvas automatically. You can specify to do this without breaking the event loop (i.e. you still click "Continue" and use the event viewer like normal, and all the canvases are saved), or you can simply have it iterate through by itself and save the canvases for you. The example config uses the latter option.
