### ISSUE TITLE
Frequency spectra produced from ROACH egg files are backwards

### ISSUE THREAD

**Issue by nsoblath** [project8/katydid#80]
When Katydid reads egg files of ROACH data produced with Psyllid, the frequency axis produced is reversed.

The attached spectrum is of an 800 MHz tone, where the ROACH channel was centered at approximately 820 MHz.  The tone should show up near 50-20=30 MHz, but instead shows up near 50+20=70 MHz.

![test_12-28-16_eth1_fs](https://cloud.githubusercontent.com/assets/829991/21535068/f61c6026-cd24-11e6-9a79-a1d3bda1d372.png)

If I open the egg file with python's h5py and do an FFT with numpy, the spectrum comes out correctly.  This is the technique used in dragonfly's Roach2Interface:: screenshot_T_packets.  This function can be used to test it:
```python
def plot_fs(file, record):
    t_orig = file["streams"]["stream0"]["acquisitions"]["0"][record]
    t_comp = np.array(t_orig[1::2] + 1j*t_orig[0::2], dtype=np.complex64)
    f = np.abs(np.fft.fftshift(np.fft.fft(t_comp)))
    plt.plot(np.linspace(0, 100, np.shape(t_comp)[0]), 10.0*np.log10(f), color='b')
```

So far I don't know why this is happening.  When RSA files are read (when uses the same functions in KTForwardFFTW), the spectra come out correctly, as evidenced by the fact that electron tracks go up in frequency.

**Comment by laroque** [comment]
Is this using the exact same complex fft methods? The DDC shifts data into negative frequencies so that the 770-870 should show up in -50 to 50 and needs to be shifted up (same as the RSA data); this is subtle in the way that FFTW populates the output arrays but I'm a bit confused because I thought it was a solved problem from various debugging of RSA data.

**Comment by nsoblath** [comment]
Yes, it's using the exact same complex FFT methods.  The frequency range would be -50 to 50 MHz, except for the correction that we put in when we were debugging with the RSA data.  That correction shifts the frequency range up to 0 to 100 MHz for IQ data.

I'm pretty sure it's not an issue with the bin ordering in the output array from FFTW.  The FFT in numpy also has the same ordering.  In the python code the function numpy.fftshift switches the bin ordering so it's in frequency order.  In Katydid the array subscript operator hides the FFTW ordering from the user.  I can see that there's no bin ordering difference between what Katydid does and what the python code does just by transforming the same data and looking at the sequence of peaks in the output.

**Comment by laroque** [comment]
After discussing with Noah earlier, it seems plausible that somewhere katydid is swapping the I and Q values for roach data. This is consistent with the evidence:
1) katydid works for RSA data
2) FFT and everything downstream of that are identical
3) numpy processing matches expectations for tones, so not a problem with the data iself
4) spectra appear to be fully mirror reversed, not folded (as happens with FFTW output ordering)

All of this was discussed earlier, but since the issue is still open I wanted to post this as a reminder to ourselves (or anyone following along) so we don't forget.

**Comment by nsoblath** [comment]
I tested Katydid at every stage between raw time series and the FFT processor, and the bin orderings were completely consistent.  So whatever the issue it doesn't appear to be in Katydid.

Once I was thinking about this, though, as I looked back at the code that creates the complex array in phasmid/.../r2daq.py, I realized that it's actually flipping the I and Q ordering from what I would have expected it to have:

```python
x = array(self.data[1::2] + 1j*self.data[0::2],dtype=complex64)
```

Note that the I component starts with element 1, and the Q component starts with element 0, not the other way around.

I can take the code in r2daq.py at its word and calculate backward what the bin ordering in the UDP packet payloads must be:

We want to end up with the true order, `(I0, Q0), (I1, Q1), (I2, Q2), (I3, Q3), (I4, Q4), . . .`

Packet::interpret_data() must have started with: `Q0, I0, Q1, I1, Q2, I2, Q3, I3, Q4, I4, . . .`

Then the original packet payload was: `I3, Q3, I2, Q2, I1, Q1, I0, Q0, I7, Q7, . . .`

This would then be a Psyllid issue to parse those packets correctly so that the egg file contains arrays in this order:  `I0, Q0, I1, Q1, I2, Q2, I3, Q3, I4, Q4, . . .`

I've written to André to clarify what's in the UDP packet payloads and to try to understand why it's that way.  The original description I was given for the payloads (and therefore my previous operating assumption) was that "the samples are in the correct order."  Hopefully we can get this cleared up quickly.

**Comment by nsoblath** [comment]
Ok, I think we've got it now.  André confirms what I said above about the byte ordering.  I'll make the necessary changes in Psyllid.  I'll discuss those details in project8/psyllid#22.  Nothing needs to be done in Katydid for this issue.

**Comment by nsoblath** [comment]
This was fixed in Psyllid a few days ago.  See project8/psyllid#22.
