### ISSUE TITLE
ROOT and H5 writer inconsistencies

### ISSUE THREAD

**Issue by guiguem** [project8/katydid#89]
It seems that the h5 and root files saved by the writers do not contain the same informations: some fields are different:
h5/candidate_tracks:
- EventID

root/fTracks branch:
- fUniqueID
- fBits
- @size

More differences exist between the multiTracksEvents tree and the candidate group.
Finally the egg header is not saved in the root file and does contain obsolete fields (such as mantis_timestamp)

**Comment by nsoblath** [comment]
Fixed and tested as of commit cade82a1e4607256a4202fbefb5eca4d26ea3acc.
