### ISSUE TITLE
processed roach data has egg-header central frequency 25MHz

### ISSUE THREAD

**Issue by cclaessens** [project8/katydid#98]
I noticed this for the roach data in the runs 2912 to 2992. Every second of those runs is a roach run.
The rf roi min and max values on dirac showed the correct frequencies. 
The meta data in the actual egg files also shows the correct frequencies.

Therefore I suspect that the issue is in the egg3 reader or some other roach data specific part of katydid.

**Comment by nsoblath** [comment]
This appears to be related to #86, so I'll close it as a duplicate.
